export const tempRiverData = [
    {
        "id": 109,
        "name": "Ball Mountain Brook",
        "url": "ballmountainbrook",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "WEST RIVER AT JAMAICA, VT",
        "gauge1ID": "01155500",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "174",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 110,
        "name": "Barton River",
        "url": "bartonriver",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "C",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "BARTON RIVER NEAR COVENTRY, VT",
        "gauge1ID": "04296280",
        "gauge1RisingMax": 850,
        "gauge1RisingMin": 350,
        "gauge1SteadyMax": 900,
        "gauge1SteadyMin": 400,
        "gauge1FallingMax": 950,
        "gauge1FallingMin": 450,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "314",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": -2,
        "gauge1Trend": "steady",
        "gauge1Max": 900,
        "gauge1Min": 400,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 79
    },
    {
        "id": 111,
        "name": "Big Branch of Otter Creek",
        "url": "thebigbranch",
        "difficultyNum": 13,
        "difficultyChar": "V",
        "quality": "A+",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/11/Big-Branch.jpg",
        "riverCam": "bigbranch",
        "gauge1Name": "OTTAUQUECHEE RIVER NEAR WEST BRIDGEWATER, VT",
        "gauge1ID": "01150900",
        "gauge1RisingMax": 250,
        "gauge1RisingMin": 150,
        "gauge1SteadyMax": 350,
        "gauge1SteadyMin": 125,
        "gauge1FallingMax": 400,
        "gauge1FallingMin": 150,
        "gauge2Name": "OTTER CREEK AT CENTER RUTLAND, VT",
        "gauge2ID": "04282000",
        "gauge2RisingMax": 1800,
        "gauge2RisingMin": 750,
        "gauge2SteadyMax": 2000,
        "gauge2SteadyMin": 900,
        "gauge2FallingMax": 3000,
        "gauge2FallingMin": 1200,
        "gauge1Reading": "29.9",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 350,
        "gauge1Min": 125,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 24
    },
    {
        "id": 112,
        "name": "Bingo Brook",
        "url": "bingobrook",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "AYERS BROOK AT RANDOLPH, VT",
        "gauge1ID": "01142500",
        "gauge1RisingMax": 450,
        "gauge1RisingMin": 175,
        "gauge1SteadyMax": 500,
        "gauge1SteadyMin": 200,
        "gauge1FallingMax": 550,
        "gauge1FallingMin": 225,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "30.9",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": -1,
        "gauge1Trend": "steady",
        "gauge1Max": 500,
        "gauge1Min": 200,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 15
    },
    {
        "id": 113,
        "name": "Bristol Notch Brook",
        "url": "bristolnotch",
        "difficultyNum": 12,
        "difficultyChar": "V-",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "NEW HAVEN RIVER @ BROOKSVILLE, NR MIDDLEBURY, VT",
        "gauge1ID": "04282525",
        "gauge1RisingMax": 1300,
        "gauge1RisingMin": 750,
        "gauge1SteadyMax": 1500,
        "gauge1SteadyMin": 900,
        "gauge1FallingMax": 1750,
        "gauge1FallingMin": 1100,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "122",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 1500,
        "gauge1Min": 900,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 14
    },
    {
        "id": 114,
        "name": "Browns River (Jericho)",
        "url": "brownsriverjericho",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2020/05/BrownsRiverJericho2.jpg",
        "riverCam": "",
        "gauge1Name": "RANCH BROOK AT RANCH CAMP, NEAR STOWE, VT",
        "gauge1ID": "04288230",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "6.51",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 115,
        "name": "Browns River (Lower)",
        "url": "brosnwriverlower",
        "difficultyNum": 8,
        "difficultyChar": "III+",
        "quality": "B-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "LAMOILLE RIVER AT EAST GEORGIA, VT",
        "gauge1ID": "04292500",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "1160",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": -10,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 116,
        "name": "Brush Brook",
        "url": "brushbrook",
        "difficultyNum": 11,
        "difficultyChar": "IV+",
        "quality": "C",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "LEWIS CREEK AT NORTH FERRISBURG, VT",
        "gauge1ID": "04282780",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "67.5",
        "gauge1DateTime": "2024-05-19T20:15:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 117,
        "name": "Cobb Brook",
        "url": "cobbbrook",
        "difficultyNum": 11,
        "difficultyChar": "IV+",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "LEWIS CREEK AT NORTH FERRISBURG, VT",
        "gauge1ID": "04282780",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "67.5",
        "gauge1DateTime": "2024-05-19T20:15:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 118,
        "name": "Cold River",
        "url": "thecold",
        "difficultyNum": 9,
        "difficultyChar": "IV-",
        "quality": "A-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "OTTER CREEK AT CENTER RUTLAND, VT",
        "gauge1ID": "04282000",
        "gauge1RisingMax": 3500,
        "gauge1RisingMin": 1500,
        "gauge1SteadyMax": 3750,
        "gauge1SteadyMin": 1750,
        "gauge1FallingMax": 4000,
        "gauge1FallingMin": 2000,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null
    },
    {
        "id": 119,
        "name": "Devil's Washbowl",
        "url": "devilswashbowl",
        "difficultyNum": 11,
        "difficultyChar": "IV+",
        "quality": "A-",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/07/DWB.jpg",
        "riverCam": "",
        "gauge1Name": "DOG RIVER AT NORTHFIELD FALLS, VT",
        "gauge1ID": "04287000",
        "gauge1RisingMax": 2800,
        "gauge1RisingMin": 1500,
        "gauge1SteadyMax": 2900,
        "gauge1SteadyMin": 1625,
        "gauge1FallingMax": 3000,
        "gauge1FallingMin": 1750,
        "gauge2Name": "AYERS BROOK AT RANDOLPH, VT",
        "gauge2ID": "01142500",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "79.5",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 2900,
        "gauge1Min": 1625,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 5
    },
    {
        "id": 120,
        "name": "East Granville Brook",
        "url": "eastgranvillebrook",
        "difficultyNum": 13,
        "difficultyChar": "V",
        "quality": "A-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "AYERS BROOK AT RANDOLPH, VT",
        "gauge1ID": "01142500",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": "DOG RIVER AT NORTHFIELD FALLS, VT",
        "gauge2ID": "04287000",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "30.9",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": -1,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 121,
        "name": "Flint Brook",
        "url": "flintbrook",
        "difficultyNum": 12,
        "difficultyChar": "V-",
        "quality": "A-",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/05/Flint-Brook.jpg",
        "riverCam": "",
        "gauge1Name": "DOG RIVER AT NORTHFIELD FALLS, VT",
        "gauge1ID": "04287000",
        "gauge1RisingMax": 1800,
        "gauge1RisingMin": 900,
        "gauge1SteadyMax": 2150,
        "gauge1SteadyMin": 1000,
        "gauge1FallingMax": 2500,
        "gauge1FallingMin": 1100,
        "gauge2Name": "AYERS BROOK AT RANDOLPH, VT",
        "gauge2ID": "01142500",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "79.5",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 2150,
        "gauge1Min": 1000,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 8
    },
    {
        "id": 122,
        "name": "Foote Brook",
        "url": "footebrook",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "C",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "RANCH BROOK AT RANCH CAMP, NEAR STOWE, VT",
        "gauge1ID": "04288230",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": "LAMOILLE RIVER AT JOHNSON, VT",
        "gauge2ID": "04292000",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "6.51",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 123,
        "name": "Furnace Brook",
        "url": "furnacebrook",
        "difficultyNum": 12,
        "difficultyChar": "V-",
        "quality": "B+",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "OTTAUQUECHEE RIVER NEAR WEST BRIDGEWATER, VT",
        "gauge1ID": "01150900",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "29.9",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 124,
        "name": "Gihon River",
        "url": "thegihon",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "A",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/05/The-Gihon.jpg",
        "riverCam": "",
        "gauge1Name": "LAMOILLE RIVER AT JOHNSON, VT",
        "gauge1ID": "04292000",
        "gauge1RisingMax": 2000,
        "gauge1RisingMin": 1250,
        "gauge1SteadyMax": 2200,
        "gauge1SteadyMin": 1350,
        "gauge1FallingMax": 2500,
        "gauge1FallingMin": 1500,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "496",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": -5,
        "gauge1Trend": "steady",
        "gauge1Max": 2200,
        "gauge1Min": 1350,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 37
    },
    {
        "id": 125,
        "name": "Green River",
        "url": "thegreen",
        "difficultyNum": 11,
        "difficultyChar": "IV+",
        "quality": "A",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/05/TheGreen.jpg",
        "riverCam": "",
        "gauge1Name": "",
        "gauge1ID": "",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null
    },
    {
        "id": 126,
        "name": "Joe's Brook",
        "url": "joesbrook",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B+",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/11/Joes-Brook.jpg",
        "riverCam": "",
        "gauge1Name": "SLEEPERS RIVER (SITE W-5) NEAR ST. JOHNSBURY, VT",
        "gauge1ID": "01135300",
        "gauge1RisingMax": 800,
        "gauge1RisingMin": 250,
        "gauge1SteadyMax": 900,
        "gauge1SteadyMin": 275,
        "gauge1FallingMax": 1100,
        "gauge1FallingMin": 300,
        "gauge2Name": "POPE BROOK (SITE W-3) NEAR NORTH DANVILLE, VT",
        "gauge2ID": "01135150",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "50.9",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": -1,
        "gauge1Trend": "steady",
        "gauge1Max": 900,
        "gauge1Min": 275,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 19
    },
    {
        "id": 127,
        "name": "Joiner Brook",
        "url": "joinerbrook",
        "difficultyNum": 13,
        "difficultyChar": "V",
        "quality": "B+",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "RANCH BROOK AT RANCH CAMP, NEAR STOWE, VT",
        "gauge1ID": "04288230",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": "W BRANCH LITTLE R ABV BINGHAM FALLS NEAR STOWE, VT",
        "gauge2ID": "04288225",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "6.51",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 128,
        "name": "Kenfield Brook (Terrill Gorge)",
        "url": "thekenfield",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "A-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "RANCH BROOK AT RANCH CAMP, NEAR STOWE, VT",
        "gauge1ID": "04288230",
        "gauge1RisingMax": 250,
        "gauge1RisingMin": 75,
        "gauge1SteadyMax": 300,
        "gauge1SteadyMin": 85,
        "gauge1FallingMax": 350,
        "gauge1FallingMin": 100,
        "gauge2Name": "W BRANCH LITTLE R ABV BINGHAM FALLS NEAR STOWE, VT",
        "gauge2ID": "04288225",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "6.51",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 300,
        "gauge1Min": 85,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 8
    },
    {
        "id": 129,
        "name": "Lamoille (Lower)",
        "url": "lamoillelower",
        "difficultyNum": 6,
        "difficultyChar": "III-",
        "quality": "B-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "LAMOILLE RIVER AT EAST GEORGIA, VT",
        "gauge1ID": "04292500",
        "gauge1RisingMax": 10000,
        "gauge1RisingMin": 1000,
        "gauge1SteadyMax": 11000,
        "gauge1SteadyMin": 1200,
        "gauge1FallingMax": 12000,
        "gauge1FallingMin": 1200,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "1160",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": -10,
        "gauge1Trend": "steady",
        "gauge1Max": 11000,
        "gauge1Min": 1200,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 97
    },
    {
        "id": 130,
        "name": "Mad River (Lower)",
        "url": "lowermad",
        "difficultyNum": 7,
        "difficultyChar": "III",
        "quality": "B+",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2023/07/MadRiver.jpg",
        "riverCam": "",
        "gauge1Name": "MAD RIVER NEAR MORETOWN, VT",
        "gauge1ID": "04288000",
        "gauge1RisingMax": 4500,
        "gauge1RisingMin": 250,
        "gauge1SteadyMax": 5000,
        "gauge1SteadyMin": 300,
        "gauge1FallingMax": 5500,
        "gauge1FallingMin": 325,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "144",
        "gauge1DateTime": "2024-05-19T20:00:00.000-04:00",
        "gauge1ChangePerHr": -3,
        "gauge1Trend": "steady",
        "gauge1Max": 5000,
        "gauge1Min": 300,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 48
    },
    {
        "id": 131,
        "name": "Mad River (Upper)",
        "url": "uppermad",
        "difficultyNum": 9,
        "difficultyChar": "IV-",
        "quality": "C",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2024/04/MadRiverUpper.jpg",
        "riverCam": "",
        "gauge1Name": "MAD RIVER NEAR MORETOWN, VT",
        "gauge1ID": "04288000",
        "gauge1RisingMax": 5000,
        "gauge1RisingMin": 1500,
        "gauge1SteadyMax": 5500,
        "gauge1SteadyMin": 1700,
        "gauge1FallingMax": 6000,
        "gauge1FallingMin": 1900,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "144",
        "gauge1DateTime": "2024-05-19T20:00:00.000-04:00",
        "gauge1ChangePerHr": -3,
        "gauge1Trend": "steady",
        "gauge1Max": 5500,
        "gauge1Min": 1700,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 8
    },
    {
        "id": 132,
        "name": "Middlebury River",
        "url": "themiddleburygorge",
        "difficultyNum": 13,
        "difficultyChar": "V",
        "quality": "A+",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2020/11/%E2%81%AFMiddleburyGorge.jpg",
        "riverCam": "middlebury",
        "gauge1Name": "NEW HAVEN RIVER @ BROOKSVILLE, NR MIDDLEBURY, VT",
        "gauge1ID": "04282525",
        "gauge1RisingMax": 450,
        "gauge1RisingMin": 200,
        "gauge1SteadyMax": 550,
        "gauge1SteadyMin": 225,
        "gauge1FallingMax": 650,
        "gauge1FallingMin": 250,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "122",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 550,
        "gauge1Min": 225,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 54
    },
    {
        "id": 133,
        "name": "Mill Brook (Danby Slides)",
        "url": "millbrookdanby",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B+",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "OTTER CREEK AT CENTER RUTLAND, VT",
        "gauge1ID": null,
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null
    },
    {
        "id": 134,
        "name": "Mill Brook (Jericho)",
        "url": "millbrookjericho",
        "difficultyNum": 9,
        "difficultyChar": "IV-",
        "quality": "B-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "RANCH BROOK AT RANCH CAMP, NEAR STOWE, VT",
        "gauge1ID": "04288230",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "6.51",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 135,
        "name": "Mill River (Clarendon Gorge)",
        "url": "clarendongorge",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B+",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2021/09/ClarendonGorge.jpg",
        "riverCam": "",
        "gauge1Name": "OTTER CREEK AT CENTER RUTLAND, VT",
        "gauge1ID": null,
        "gauge1RisingMax": 2000,
        "gauge1RisingMin": 750,
        "gauge1SteadyMax": 2250,
        "gauge1SteadyMin": 850,
        "gauge1FallingMax": 2500,
        "gauge1FallingMin": 950,
        "gauge2Name": "OTTAUQUECHEE RIVER NEAR WEST BRIDGEWATER, VT",
        "gauge2ID": "01150900",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null
    },
    {
        "id": 136,
        "name": "Missisquoi River (Sheldon Springs)",
        "url": "missisquoiriversheldonsprings",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B+",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2020/04/Missisquoi.jpg",
        "riverCam": "",
        "gauge1Name": "MISSISQUOI RIVER AT SWANTON, VT",
        "gauge1ID": "04294000",
        "gauge1RisingMax": 6000,
        "gauge1RisingMin": 3400,
        "gauge1SteadyMax": 7500,
        "gauge1SteadyMin": 3650,
        "gauge1FallingMax": 9000,
        "gauge1FallingMin": 3900,
        "gauge2Name": "MISSISQUOI RIVER NEAR EAST BERKSHIRE, VT",
        "gauge2ID": "04293500",
        "gauge2RisingMax": 4500,
        "gauge2RisingMin": 1600,
        "gauge2SteadyMax": 4750,
        "gauge2SteadyMin": 1800,
        "gauge2FallingMax": 5000,
        "gauge2FallingMin": 2000,
        "gauge1Reading": "1330",
        "gauge1DateTime": "2024-05-19T19:45:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 7500,
        "gauge1Min": 3650,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 36
    },
    {
        "id": 137,
        "name": "Moose River (Lower)",
        "url": "lowermoose",
        "difficultyNum": 8,
        "difficultyChar": "III+",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "MOOSE RIVER AT VICTORY, VT",
        "gauge1ID": "01134500",
        "gauge1RisingMax": 1000,
        "gauge1RisingMin": 300,
        "gauge1SteadyMax": 1500,
        "gauge1SteadyMin": 400,
        "gauge1FallingMax": 2000,
        "gauge1FallingMin": 500,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "113",
        "gauge1DateTime": "2024-05-19T20:00:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 1500,
        "gauge1Min": 400,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 28
    },
    {
        "id": 138,
        "name": "Moose River (Top)",
        "url": "topmoose",
        "difficultyNum": 9,
        "difficultyChar": "IV-",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "MOOSE RIVER AT VICTORY, VT",
        "gauge1ID": "01134500",
        "gauge1RisingMax": 2600,
        "gauge1RisingMin": 475,
        "gauge1SteadyMax": 2800,
        "gauge1SteadyMin": 525,
        "gauge1FallingMax": 3000,
        "gauge1FallingMin": 600,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "113",
        "gauge1DateTime": "2024-05-19T20:00:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 2800,
        "gauge1Min": 525,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 22
    },
    {
        "id": 139,
        "name": "Moose River (Upper)",
        "url": "uppermoose",
        "difficultyNum": 7,
        "difficultyChar": "III",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "MOOSE RIVER AT VICTORY, VT",
        "gauge1ID": "01134500",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "113",
        "gauge1DateTime": "2024-05-19T20:00:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 140,
        "name": "New Haven (Ledges)",
        "url": "newhavenledges",
        "difficultyNum": 11,
        "difficultyChar": "IV+",
        "quality": "A+",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/05/New-Haven-Ledges.jpg",
        "riverCam": "newhaven",
        "gauge1Name": "NEW HAVEN RIVER @ BROOKSVILLE, NR MIDDLEBURY, VT",
        "gauge1ID": "04282525",
        "gauge1RisingMax": 1100,
        "gauge1RisingMin": 350,
        "gauge1SteadyMax": 1200,
        "gauge1SteadyMin": 375,
        "gauge1FallingMax": 1300,
        "gauge1FallingMin": 400,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "122",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 1200,
        "gauge1Min": 375,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 33
    },
    {
        "id": 141,
        "name": "New Haven (Lower)",
        "url": "lowernewhaven",
        "difficultyNum": 8,
        "difficultyChar": "III+",
        "quality": "B+",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/05/New-Haven-Lower.jpg",
        "riverCam": "",
        "gauge1Name": "NEW HAVEN RIVER @ BROOKSVILLE, NR MIDDLEBURY, VT",
        "gauge1ID": "04282525",
        "gauge1RisingMax": 4000,
        "gauge1RisingMin": 750,
        "gauge1SteadyMax": 6000,
        "gauge1SteadyMin": 900,
        "gauge1FallingMax": 7000,
        "gauge1FallingMin": 1000,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "122",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 6000,
        "gauge1Min": 900,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 14
    },
    {
        "id": 142,
        "name": "New Haven (Upper)",
        "url": "uppernewhaven",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B+",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "NEW HAVEN RIVER @ BROOKSVILLE, NR MIDDLEBURY, VT",
        "gauge1ID": "04282525",
        "gauge1RisingMax": 1200,
        "gauge1RisingMin": 600,
        "gauge1SteadyMax": 1500,
        "gauge1SteadyMin": 725,
        "gauge1FallingMax": 1800,
        "gauge1FallingMin": 850,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "122",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 1500,
        "gauge1Min": 725,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 17
    },
    {
        "id": 143,
        "name": "North Branch of The Lamoille",
        "url": "northbranchlamoille",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "A-",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/05/NB-Lamoille.jpg",
        "riverCam": "northbranchlamoille",
        "gauge1Name": "LAMOILLE RIVER AT JOHNSON, VT",
        "gauge1ID": "04292000",
        "gauge1RisingMax": 8000,
        "gauge1RisingMin": 1500,
        "gauge1SteadyMax": 9000,
        "gauge1SteadyMin": 2000,
        "gauge1FallingMax": 10000,
        "gauge1FallingMin": 2250,
        "gauge2Name": "LAMOILLE RIVER AT EAST GEORGIA, VT",
        "gauge2ID": "04292500",
        "gauge2RisingMax": 12000,
        "gauge2RisingMin": 3750,
        "gauge2SteadyMax": 14000,
        "gauge2SteadyMin": 4500,
        "gauge2FallingMax": 16000,
        "gauge2FallingMin": 5250,
        "gauge1Reading": "496",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": -5,
        "gauge1Trend": "steady",
        "gauge1Max": 9000,
        "gauge1Min": 2000,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 25
    },
    {
        "id": 144,
        "name": "North Branch of The Winooski",
        "url": "northbranchwinooski",
        "difficultyNum": 11,
        "difficultyChar": "IV+",
        "quality": "A",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/05/NB-Winooski.jpg",
        "riverCam": "",
        "gauge1Name": "LITTLE RIVER NEAR STOWE, VT",
        "gauge1ID": "04288295",
        "gauge1RisingMax": 2000,
        "gauge1RisingMin": 425,
        "gauge1SteadyMax": 2600,
        "gauge1SteadyMin": 500,
        "gauge1FallingMax": 3200,
        "gauge1FallingMin": 575,
        "gauge2Name": "RANCH BROOK AT RANCH CAMP, NEAR STOWE, VT",
        "gauge2ID": "04288230",
        "gauge2RisingMax": 200,
        "gauge2RisingMin": 60,
        "gauge2SteadyMax": 275,
        "gauge2SteadyMin": 75,
        "gauge2FallingMax": 350,
        "gauge2FallingMin": 90,
        "gauge1Reading": "99.2",
        "gauge1DateTime": "2024-05-19T19:45:00.000-04:00",
        "gauge1ChangePerHr": -2,
        "gauge1Trend": "steady",
        "gauge1Max": 2600,
        "gauge1Min": 500,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 20
    },
    {
        "id": 145,
        "name": "Nulhegan River",
        "url": "thenulhegan",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "EAST BRANCH PASSUMPSIC RIVER NEAR EAST HAVEN, VT",
        "gauge1ID": "01133000",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": "MOOSE RIVER AT VICTORY, VT",
        "gauge2ID": "01134500",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "159",
        "gauge1DateTime": "2024-05-19T20:00:00.000-04:00",
        "gauge1ChangePerHr": -2,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 146,
        "name": "Ottaquechee River",
        "url": "theottaquechee",
        "difficultyNum": 8,
        "difficultyChar": "III+",
        "quality": "B-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "OTTAUQUECHEE RIVER AT NORTH HARTLAND, VT",
        "gauge1ID": "01151500",
        "gauge1RisingMax": 1500,
        "gauge1RisingMin": 200,
        "gauge1SteadyMax": 1750,
        "gauge1SteadyMin": 250,
        "gauge1FallingMax": 2000,
        "gauge1FallingMin": 300,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "283",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 1750,
        "gauge1Min": 250,
        "levelStatus": "running",
        "flowBarColor": "green",
        "flowBarPercent": 2
    },
    {
        "id": 147,
        "name": "Otter Creek",
        "url": "ottercreek",
        "difficultyNum": 6,
        "difficultyChar": "III-",
        "quality": "B-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "OTTER CREEK AT MIDDLEBURY, VT",
        "gauge1ID": "04282500",
        "gauge1RisingMax": 6500,
        "gauge1RisingMin": 300,
        "gauge1SteadyMax": 6500,
        "gauge1SteadyMin": 300,
        "gauge1FallingMax": 6500,
        "gauge1FallingMin": 300,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "910",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": -8,
        "gauge1Trend": "steady",
        "gauge1Max": 6500,
        "gauge1Min": 300,
        "levelStatus": "running",
        "flowBarColor": "green",
        "flowBarPercent": 10
    },
    {
        "id": 148,
        "name": "Patterson Brook (Upper White River)",
        "url": "patterson",
        "difficultyNum": 9,
        "difficultyChar": "IV-",
        "quality": "A",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/07/Patterson.jpg",
        "riverCam": "",
        "gauge1Name": "AYERS BROOK AT RANDOLPH, VT",
        "gauge1ID": "01142500",
        "gauge1RisingMax": 450,
        "gauge1RisingMin": 150,
        "gauge1SteadyMax": 600,
        "gauge1SteadyMin": 175,
        "gauge1FallingMax": 750,
        "gauge1FallingMin": 200,
        "gauge2Name": "NEW HAVEN RIVER @ BROOKSVILLE, NR MIDDLEBURY, VT",
        "gauge2ID": "04282525",
        "gauge2RisingMax": 3500,
        "gauge2RisingMin": 600,
        "gauge2SteadyMax": 3750,
        "gauge2SteadyMin": 750,
        "gauge2FallingMax": 4000,
        "gauge2FallingMin": 900,
        "gauge1Reading": "30.9",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": -1,
        "gauge1Trend": "steady",
        "gauge1Max": 600,
        "gauge1Min": 175,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 18
    },
    {
        "id": 149,
        "name": "Pauls Stream (Lower)",
        "url": "lowerpauls",
        "difficultyNum": 9,
        "difficultyChar": "IV-",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "EAST BRANCH PASSUMPSIC RIVER NEAR EAST HAVEN, VT",
        "gauge1ID": "01133000",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": "MOOSE RIVER AT VICTORY, VT",
        "gauge2ID": "01134500",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "159",
        "gauge1DateTime": "2024-05-19T20:00:00.000-04:00",
        "gauge1ChangePerHr": -2,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 150,
        "name": "Pauls Stream (Upper)",
        "url": "upperpauls",
        "difficultyNum": 7,
        "difficultyChar": "III",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "EAST BRANCH PASSUMPSIC RIVER NEAR EAST HAVEN, VT",
        "gauge1ID": "01133000",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": "MOOSE RIVER AT VICTORY, VT",
        "gauge2ID": "01134500",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "159",
        "gauge1DateTime": "2024-05-19T20:00:00.000-04:00",
        "gauge1ChangePerHr": -2,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 151,
        "name": "Poultney River (Lower)",
        "url": "lowerpoultney",
        "difficultyNum": 8,
        "difficultyChar": "III+",
        "quality": "C+",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "POULTNEY RIVER BELOW FAIR HAVEN, VT",
        "gauge1ID": "04280000",
        "gauge1RisingMax": 2000,
        "gauge1RisingMin": 200,
        "gauge1SteadyMax": 2500,
        "gauge1SteadyMin": 300,
        "gauge1FallingMax": 3000,
        "gauge1FallingMin": 400,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "204",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": -2,
        "gauge1Trend": "steady",
        "gauge1Max": 2500,
        "gauge1Min": 300,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 68
    },
    {
        "id": 152,
        "name": "Poultney River (Upper)",
        "url": "upperpoultney",
        "difficultyNum": 8,
        "difficultyChar": "III+",
        "quality": "C+",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "POULTNEY RIVER BELOW FAIR HAVEN, VT",
        "gauge1ID": "04280000",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "204",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": -2,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 153,
        "name": "Ridley Brook",
        "url": "ridley",
        "difficultyNum": 12,
        "difficultyChar": "V-",
        "quality": "A",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/05/Ridley.jpg",
        "riverCam": "",
        "gauge1Name": "RANCH BROOK AT RANCH CAMP, NEAR STOWE, VT",
        "gauge1ID": "04288230",
        "gauge1RisingMax": 100,
        "gauge1RisingMin": 65,
        "gauge1SteadyMax": 200,
        "gauge1SteadyMin": 75,
        "gauge1FallingMax": 125,
        "gauge1FallingMin": 70,
        "gauge2Name": "MAD RIVER NEAR MORETOWN, VT",
        "gauge2ID": "04288000",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "6.51",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 200,
        "gauge1Min": 75,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 9
    },
    {
        "id": 154,
        "name": "Roaring Branch of the Battenkill",
        "url": "roaringbranch",
        "difficultyNum": 12,
        "difficultyChar": "V-",
        "quality": "B+",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "WALLOOMSAC RIVER NEAR NORTH BENNINGTON, VT",
        "gauge1ID": "01334000",
        "gauge1RisingMax": 1500,
        "gauge1RisingMin": 370,
        "gauge1SteadyMax": 1750,
        "gauge1SteadyMin": 450,
        "gauge1FallingMax": 2000,
        "gauge1FallingMin": 550,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "174",
        "gauge1DateTime": "2024-05-19T20:15:00.000-04:00",
        "gauge1ChangePerHr": -3,
        "gauge1Trend": "steady",
        "gauge1Max": 1750,
        "gauge1Min": 450,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 39
    },
    {
        "id": 155,
        "name": "Rock River",
        "url": "therock",
        "difficultyNum": 8,
        "difficultyChar": "III+",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "GREEN RIVER NEAR COLRAIN, MA",
        "gauge1ID": "01170100",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "57.7",
        "gauge1DateTime": "2024-05-19T20:00:00.000-04:00",
        "gauge1ChangePerHr": -1,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 156,
        "name": "Sterling Brook",
        "url": "sterlingbrook",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "RANCH BROOK AT RANCH CAMP, NEAR STOWE, VT",
        "gauge1ID": "04288230",
        "gauge1RisingMax": 300,
        "gauge1RisingMin": 75,
        "gauge1SteadyMax": 500,
        "gauge1SteadyMin": 120,
        "gauge1FallingMax": 450,
        "gauge1FallingMin": 100,
        "gauge2Name": "W BRANCH LITTLE R ABV BINGHAM FALLS NEAR STOWE, VT",
        "gauge2ID": "04288225",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "6.51",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 500,
        "gauge1Min": 120,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 5
    },
    {
        "id": 157,
        "name": "Stony Brook",
        "url": "stonybrook",
        "difficultyNum": 9,
        "difficultyChar": "IV-",
        "quality": "C",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "DOG RIVER AT NORTHFIELD FALLS, VT",
        "gauge1ID": "04287000",
        "gauge1RisingMax": 2200,
        "gauge1RisingMin": 1000,
        "gauge1SteadyMax": 2500,
        "gauge1SteadyMin": 1500,
        "gauge1FallingMax": 3000,
        "gauge1FallingMin": 1750,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "79.5",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 2500,
        "gauge1Min": 1500,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 5
    },
    {
        "id": 158,
        "name": "Trout River",
        "url": "thetrout",
        "difficultyNum": 11,
        "difficultyChar": "IV+",
        "quality": "B+",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/11/The-Trout.jpg",
        "riverCam": "",
        "gauge1Name": "MISSISQUOI RIVER NEAR EAST BERKSHIRE, VT",
        "gauge1ID": "04293500",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "849",
        "gauge1DateTime": "2024-05-19T19:45:00.000-04:00",
        "gauge1ChangePerHr": -13,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 159,
        "name": "Wardsboro Brook",
        "url": "wardsborobrook",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "WALLOOMSAC RIVER NEAR NORTH BENNINGTON, VT",
        "gauge1ID": "01334000",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": "WEST RIVER AT JAMAICA, VT",
        "gauge2ID": "01155500",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "174",
        "gauge1DateTime": "2024-05-19T20:15:00.000-04:00",
        "gauge1ChangePerHr": -3,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 160,
        "name": "Waterman Brook",
        "url": "waterman",
        "difficultyNum": 11,
        "difficultyChar": "IV+",
        "quality": "B",
        "guideImageURL": "https://creekvt.com/wp-content/uploads/2019/11/Waterman-Brook.jpg",
        "riverCam": "",
        "gauge1Name": "RANCH BROOK AT RANCH CAMP, NEAR STOWE, VT",
        "gauge1ID": "04288230",
        "gauge1RisingMax": 175,
        "gauge1RisingMin": 65,
        "gauge1SteadyMax": 190,
        "gauge1SteadyMin": 80,
        "gauge1FallingMax": 205,
        "gauge1FallingMin": 95,
        "gauge2Name": "W BRANCH LITTLE R ABV BINGHAM FALLS NEAR STOWE, VT",
        "gauge2ID": "04288225",
        "gauge2RisingMax": 175,
        "gauge2RisingMin": 75,
        "gauge2SteadyMax": 190,
        "gauge2SteadyMin": 90,
        "gauge2FallingMax": 205,
        "gauge2FallingMin": 105,
        "gauge1Reading": "6.51",
        "gauge1DateTime": "2024-05-19T19:55:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 190,
        "gauge1Min": 80,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 8
    },
    {
        "id": 161,
        "name": "Wells River",
        "url": "thewells",
        "difficultyNum": 10,
        "difficultyChar": "IV",
        "quality": "B+",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "WELLS RIVER AT WELLS RIVER, VT",
        "gauge1ID": "01139000",
        "gauge1RisingMax": 500,
        "gauge1RisingMin": 100,
        "gauge1SteadyMax": 600,
        "gauge1SteadyMin": 125,
        "gauge1FallingMax": 700,
        "gauge1FallingMin": 150,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "117",
        "gauge1DateTime": "2024-05-19T19:45:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 600,
        "gauge1Min": 125,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 94
    },
    {
        "id": 162,
        "name": "West Branch of The Deerfield",
        "url": "westbranchdeerfield",
        "difficultyNum": 12,
        "difficultyChar": "V-",
        "quality": "A",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "WALLOOMSAC RIVER NEAR NORTH BENNINGTON, VT",
        "gauge1ID": "01334000",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "174",
        "gauge1DateTime": "2024-05-19T20:15:00.000-04:00",
        "gauge1ChangePerHr": -3,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 163,
        "name": "West River",
        "url": "thewest",
        "difficultyNum": 7,
        "difficultyChar": "III",
        "quality": "A-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "WEST RIVER AT JAMAICA, VT",
        "gauge1ID": "01155500",
        "gauge1RisingMax": 6000,
        "gauge1RisingMin": 500,
        "gauge1SteadyMax": 6500,
        "gauge1SteadyMin": 650,
        "gauge1FallingMax": 7000,
        "gauge1FallingMin": 800,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "174",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": 6500,
        "gauge1Min": 650,
        "levelStatus": "too low",
        "flowBarColor": "#ffa500",
        "flowBarPercent": 27
    },
    {
        "id": 164,
        "name": "Willard Stream",
        "url": "willardstream",
        "difficultyNum": 7,
        "difficultyChar": "III",
        "quality": "B-",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "EAST BRANCH PASSUMPSIC RIVER NEAR EAST HAVEN, VT",
        "gauge1ID": "01133000",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": "MOOSE RIVER AT VICTORY, VT",
        "gauge2ID": "01134500",
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "159",
        "gauge1DateTime": "2024-05-19T20:00:00.000-04:00",
        "gauge1ChangePerHr": -2,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    },
    {
        "id": 165,
        "name": "Winhall River",
        "url": "thewinhall",
        "difficultyNum": 7,
        "difficultyChar": "III",
        "quality": "B",
        "guideImageURL": "",
        "riverCam": "",
        "gauge1Name": "WEST RIVER AT JAMAICA, VT",
        "gauge1ID": "01155500",
        "gauge1RisingMax": null,
        "gauge1RisingMin": null,
        "gauge1SteadyMax": null,
        "gauge1SteadyMin": null,
        "gauge1FallingMax": null,
        "gauge1FallingMin": null,
        "gauge2Name": null,
        "gauge2ID": null,
        "gauge2RisingMax": null,
        "gauge2RisingMin": null,
        "gauge2SteadyMax": null,
        "gauge2SteadyMin": null,
        "gauge2FallingMax": null,
        "gauge2FallingMin": null,
        "gauge1Reading": "174",
        "gauge1DateTime": "2024-05-19T19:30:00.000-04:00",
        "gauge1ChangePerHr": 0,
        "gauge1Trend": "steady",
        "gauge1Max": null,
        "gauge1Min": null,
        "levelStatus": null,
        "flowBarColor": null,
        "flowBarPercent": null
    }
]